Task_N_Tire_Arc/UI(User Interface)/Controllers/SubjectController.cs
using BLL_Business_Logic_Layer_;
using BOL_Bussines_Object_Layer_;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI_User_Interface_.Controllers
{
    public class SubjectController : Controller
    {
        // GET: Subject
        SubjectBs objBs = new SubjectBs();
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.classes = objBs.Getclass().Select(s=> s.Class_Name ).Distinct();
            ViewBag.staff = objBs.Getstaff();
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(tb_Subject subject)
        {
            objBs.Insert(subject);
            return View();
        }
        [HttpPost]
        public ActionResult Edit(tb_Subject subject)
        {
            ViewBag.staffselected = objBs.Getstaff();
            ViewBag.classselected = objBs.Getclass();
            objBs.Update(subject);
            return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.staffselected = objBs.getstaffname(id);
            //ViewBag.selected = objBs.Getclass().Select(s=>s.Class_Name).Distinct();
            //ViewBag.selected = read;
            ViewBag.classselected = objBs.Getclass();
            var model = objBs.GetRecord(id);
            return View(model);
        }
        public ActionResult List()
        {
            var lis = objBs.GetAll();
            return View(lis);
        }
    }
}

Task_N_Tire_Arc/UI(User Interface)/Views/Subject/Create.cshtml
@model BOL_Bussines_Object_Layer_.tb_Subject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Template.cshtml";
}

<h2>Create</h2>

<div class="right_col" role="main">
    @using (Html.BeginForm("Create", "Subject"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>tb_Subject</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @*@Html.LabelFor(model => model.Sub_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sub_Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sub_Id, "", new { @class = "text-danger" })
                </div>*@
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sub_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sub_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sub_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.Stf_Id, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Stf_Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stf_Id, "", new { @class = "text-danger" })*@
                    
                    <select name="Stf_Id" class ="form-control">
                        <option>Select</option>
                        @foreach (var item in ViewBag.staff)
                        {
                    <option value="@item.Stf_Id">@item.Stf_Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.Class_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Class_Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Class_Id, "", new { @class = "text-danger" })
        </div>*@
                <select name="Class_Id" class="form-control">
                    <option>Select</option>
                    @foreach (var item in ViewBag.classes)
                    {
                        <option value="@item">@item</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Task_N_Tire_Arc/UI(User Interface)/Views/Subject/Edit.cshtml
@model BOL_Bussines_Object_Layer_.tb_Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Template.cshtml";
}

<h2>Edit</h2>
<div class="right_col" role="main">
    @using (Html.BeginForm("Edit", "Subject"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>tb_Subject</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(x => x.Sub_Id)
                @*@Html.LabelFor(model => model.Sub_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sub_Id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sub_Id, "", new { @class = "text-danger" })
                    </div>*@
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sub_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sub_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sub_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.Stf_Id, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Stf_Id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Stf_Id, "", new { @class = "text-danger" })*@
                    <select name="Stf_Id" id="Stf_Id">
                        @*<option value="@Model.Stf_Id">@Model.tb_Staff.Stf_Name</option>*@
                        @foreach (var item in ViewBag.staffselected)
                        {
                            @*<option value="@item.Stf_Id">@item.Stf_Name</option>*@
                            if (item.Isselect == 1)
                            {
                                <option value="@item.Stf_Id" selected>@item.Stf_Name</option>
                            }
                            else
                            {
                                <option value="@item.Stf_Id">@item.Stf_Name</option>

                            }

                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Class_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Class_Id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Class_Id, "", new { @class = "text-danger" })*@
                    <select name="Class_Id" id="Class_Id">
                        <option value="@Model.Class_Id">@Model.tb_Class.Class_Name @Model.tb_Class.Class_Section</option>
                        @foreach (var item in ViewBag.classselected)
                        {
                            <option value="@item.Class_Id">@item.Class_Name  @item.Class_Section</option>
                            @*if (item.Isselect == 1)
                                {
                                    <option value="@item.Class_Id" selected>@item.Class_Name</option>
                                }
                                else
                                {
                                    <option value="@item.Class_Id">@item.Class_Name</option>
                                }*@
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

<script type="text/javascript">
    @*document.getElementById("Class_Id").value = "@Model.Class_Id";
    document.getElementById("Stf_Id").value = "@Model.Stf_Id";*@
</script>

Task_N_Tire_Arc/UI(User Interface)/Views/Subject/List.cshtml
@model IEnumerable<BOL_Bussines_Object_Layer_.tb_Subject>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Template.cshtml";
}

<h2>List</h2>
<div class="right_col" role="main">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Sub_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stf_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class_Id)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sub_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sub_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stf_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Class_Id)
                </td>
                <td>
                    @Html.ActionLink("Edit/" + item.Sub_Id + "", "Subject")
                    @*<a href="@Url.Action("Edit/"+item.Sub_Id+"","Subject")" class="btn btn-success">Edit</a>*@

                </td>
            </tr>
        }

    </table>
    </div>