Task_N_Tire_Arc/UI(User Interface)/Controllers/StaffController.cs
using BLL_Business_Logic_Layer_;
using BOL_Bussines_Object_Layer_;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI_User_Interface_.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        StaffBs objBs = new StaffBs();
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Create()
        {
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(tb_Staff staff)
        {
            objBs.Insert(staff);
            return View();
        }
    }
}

Task_N_Tire_Arc/UI(User Interface)/Views/Staff/Create.cshtml
@model BOL_Bussines_Object_Layer_.tb_Staff
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Template.cshtml";
}

<h2>Create</h2>
<div class="right_col" role="main">

    @using (Html.BeginForm("Create", "Staff", FormMethod.Post))
    {
        <div class="form-group">

            <label>StaffName</label>

            <input type="text" class="form-control" name="Stf_Name" />
        </div>
        <div class="form-group">

            <label>StaffGender</label>

            <input type="text" class="form-control" name="Stf_Gender" />
        </div>
        <div class="form-group">

            <label>StaffSalary</label>

            <input type="text" class="form-control" name="Stf_Salary" />
        </div>
        <div class="form-group">

            <label>StaffCreateOnDate</label>

            <input type="text" class="form-control" name="Stf_Created_On_Date" />
        </div>
        <div class="form-group">

            <label>StaffCreatedBuy</label>

            <input type="text" class="form-control" name="Stf_Created_Buy" />
        </div>
        <div class="form-group">

            <button type="submit" class="btn btn-success">Submit</button>
        </div>

    }
</div>